stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:current-buster-slim
  artifacts:
    paths:
      - build/
  script:
    - npm install
    - npm run build

deploy-prod:
  stage: deploy
  image: helkaroui/minioclient
  dependencies:
    - build-job
  only:
    - master
  script:
    - openssl s_client -showcerts -connect s3.sharek.dev:443 > ~/.mc/certs/CAs/s3.crt
    - mc alias set s3 $MINIO_SERVER_PROD $ACCESS_KEY_PROD $SECRET_KEY_PROD
    - mc cp build/ "s3/${BUCKET_NAME_PROD}/$(date +"%Y-%m-%d")_$CI_COMMIT_SHORT_SHA/" --recursive
    - mc rm --recursive --force s3/$BUCKET_NAME_PROD/current/ || return 0
    - mc cp build/ "s3/$BUCKET_NAME_PROD/current/" --recursive

deploy-dev:
  stage: deploy
  image: helkaroui/minioclient
  dependencies:
    - build-job
  only:
    - develop
  script:
    - openssl s_client -showcerts -connect s3.sharek.dev:443 > ~/.mc/certs/CAs/s3.crt
    - mc alias set s3 $MINIO_SERVER_DEV $ACCESS_KEY_DEV $SECRET_KEY_DEV
    - mc cp build/ "s3/${BUCKET_NAME_DEV}/$(date +"%Y-%m-%d")_$CI_COMMIT_SHORT_SHA/" --recursive
    - mc rm --recursive --force s3/$BUCKET_NAME_DEV/current/ || return 0
    - mc cp build/ "s3/$BUCKET_NAME_DEV/current/" --recursive