language: node_js
node_js:
  - '12'
branches:
  only:
    - develop
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && npm run build
  - git clone https://github.com/helkaroui/helkaroui.github.io ~/$TRAVIS_BUILD_NUMBER
  - rsync -avu --delete --exclude='.git/' build/ ~/$TRAVIS_BUILD_NUMBER/
  - cd ~/$TRAVIS_BUILD_NUMBER && git push -f