language: node_js
node_js:
  - '12'
branches:
  only:
    - develop
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && npm run build
  - mkdir ~/$TRAVIS_BUILD_NUMBER
  - rsync -avu --delete build/ ~/$TRAVIS_BUILD_NUMBER/
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
  - aws s3 ls s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER/