language: node_js
node_js:
  - '12'
branches:
  only:
    - develop
cache:
  yarn: true
script:
  - pwd && ls
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - yarn && npm run build
  - git clone https://${GH_NAME}:${GH_TOKEN}@github.com/helkaroui/helkaroui.github.io ~/$TRAVIS_BUILD_NUMBER
  - rsync -avu --delete --exclude='.git/' build/ ~/$TRAVIS_BUILD_NUMBER/
  - cd ~/$TRAVIS_BUILD_NUMBER && git remote set-url origin https://${GH_NAME}:${GH_TOKEN}@github.com/helkaroui/helkaroui.github.io 
  - cd ~/$TRAVIS_BUILD_NUMBER && pwd && ls && git push -f