language: node_js
node_js:
  - '12'
branches:
  only:
    - develop
cache:
  yarn: true
script:
  - yarn && npm run build
  - export GIT_COMMIT_SHORT=$(echo "$TRAVIS_COMMIT" | cut -c1-7)
  - git clone https://${GH_TOKEN}@github.com/helkaroui/helkaroui.github.io --branch=master ~/$TRAVIS_BUILD_NUMBER
  - cp README.md build/
  - rsync -vh --recursive --delete --exclude='.git/' build/ ~/$TRAVIS_BUILD_NUMBER/
  - cd ~/$TRAVIS_BUILD_NUMBER
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/helkaroui/helkaroui.github.io 
  - echo "sharek.dev" > CNAME
  - git add . && git commit -m "[Travis-CI] based on commit=$GIT_COMMIT_SHORT build number=$TRAVIS_BUILD_NUMBER"
  - git push --set-upstream origin master