module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Docker',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'docker'
                },
            ],
        },

        {
            type: 'category',
            label: 'Kubernetes',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'kubernetes'
                },
            ],
        },
        {
            type: 'category',
            label: 'Podman',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'podman'
                },
            ],
        },
    ],
};
