module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Apache Spark',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'spark'
                },
            ],
        },
        {
            type: 'category',
            label: 'Kafka',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'kafka'
                },
            ]
        },
        {
            type: 'category',
            label: 'Flink',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'flink'
                },
            ]
        },
    ],
};
