module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Programming Languages',
            collapsed: true,
            items: [
                {
                    type: 'category',
                    label: 'Scala',
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'languages/scala'
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Python',
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'languages/python'
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Go',
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'languages/go'
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Rust',
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'languages/rust'
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Java',
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'languages/java'
                        },
                    ]
                }
            ],
        },

        {
            type: 'category',
            label: 'Compilers & Build tools',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'compilers_build_tools'
                },
            ]
        },
    ],
};
