module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Project: Scheduler',
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'scheduler'
                },
            ],
        },
    ],
};
